# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fs.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'fs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x66s.proto\"\x83\x01\n\x0b\x46sOperation\x12\x17\n\x04type\x18\x01 \x01(\x0e\x32\t.FsOpType\x12\x11\n\tsender_id\x18\x02 \x01(\t\x12\x0f\n\x07lamport\x18\x03 \x01(\x04\x12\x10\n\x08\x66ilename\x18\x04 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\t\x12\x14\n\x0cnew_filename\x18\x06 \x01(\t*9\n\x08\x46sOpType\x12\n\n\x06\x43REATE\x10\x00\x12\t\n\x05WRITE\x10\x01\x12\n\n\x06\x44\x45LETE\x10\x02\x12\n\n\x06RENAME\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FSOPTYPE']._serialized_start=146
  _globals['_FSOPTYPE']._serialized_end=203
  _globals['_FSOPERATION']._serialized_start=13
  _globals['_FSOPERATION']._serialized_end=144
# @@protoc_insertion_point(module_scope)
